name: deploy to production

on:
  push:
    branches:
      - main

jobs:
  build:
    name: build and push to docker hub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push backend-worker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./dockerfile.worker
          push: true
          tags: rajlodhi09/backend-worker:${{ github.sha }}

      - name: Clone the ops repo and update the image tag
        env:
          PAT: ${{ secrets.PAT }}
          GITHUB_SHA: ${{ github.sha }}
        run: |
          # clone ops repo
          git clone https://github.com/chemic07/chemic-ops.git
          cd chemic-ops

          # update image tag in manifest.yml
          sed -i "s|rajlodhi09/backend-worker:.*|rajlodhi09/backend-worker:${GITHUB_SHA}|g" manifest.yml

          # commit and push changes
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add manifest.yml
          git commit -m "update image to ${GITHUB_SHA}"
          git push https://${PAT}@github.com/chemic07/chemic-ops.git HEAD:main
